### ISSUE TITLE
Trouble with basic intersect using beer

### ISSUE THREAD

**Issue by Dazcam** [davetang/bedr#1]
I'm trying to use bedr to walk through the bedtools [tutorial](http://quinlanlab.org/tutorials/bedtools/bedtools.html) to understand how bedtools code translates into bedr and to compare their output.

However I'm having an issue with the main bedtools wrapper function **bedr**. I'm looking to run a basic intersection of two files **cpg.bed** and **exons.bed** provided on the link above (too large to upload here). The basic unix command for this would be:

`bedtools intersect -a cpg.bed -b exons.bed | head -5`

To emulate this line of code I tried to run the following:

```
bedr(engine = "bedtools", 
     params = "| head -5",
     input = list(a = read.table("cpg.bed"), b = read.table("exons.bed")),
     method = intersect,
     tmpDir = NULL,
     deleteTmpDir = TRUE,
     outputDir = NULL,
     outputFile = NULL,
     check.chr = TRUE,
     check.zero.based = TRUE,
     check.valid = TRUE,
     check.sort = TRUE,
     check.merge = TRUE,
     verbose = TRUE
)
```

This produces the following error message:

> Error in method == "sort" : comparison (1) is possible only for atomic and list 

Help messages on the web suggest this error may be due to R and R Studio versions being out of sync, but I have since updated to the latest versions of each and still get the same error. 

It's not clear to me from the help files and vignette provided with bedr how to input files correctly, particularly if using large files i.e. do I need to use the **read.table** function as shown above? I also tried using R objects to input the files:

`cpg <- read.table("cpg.bed")`
`exons <- read.table("exons.bed")`

Then altered the **input** parameter in the bedr command to: 

`input = list(a = cpg, b = exons)`

But I got the same error.

These files are located in my working directory. I also tried setting PARAMS to NULL, and omitting all superfluous arguments one by one, but the same error is always generated. I'm a bit stumped. 

My understanding of what this command does may be flawed, but from my reading of the help files, the first 4 arguments of the bedr function effectively constructs the line of unix code I've written above, and this is run via unix, eventually generating a new R object/or file that contains the intersect information.

**Comment by davetang** [comment]
Hi there,

I think you may have mistaken my minimal R package for something else. There are two functions in my package: 1) bed_to_granges() loads a BED file and stores it as a GRanges object and 2) intersect_bed() which performs an intersection between two GRanges objects.

Cheers,

Dave

**Comment by Dazcam** [comment]
Ah...No problem. Thanks Dave.

Best,
Darren
